#!/bin/bash

# $1 = temporary site directory
# $2 = site repo
# $3 = site root
# $4 = production site directory

rm -rf "$1" || exit 1
git clone "$2" "$1" || exit 1
if [ -d "$1/$3" ]; then
  rm -rf "$4" || exit 1
  mv "$1/$3" "$4" || exit 1
  rm -rf "$1" || exit 1
  exit 0
fi
exit 1
